### ISSUE TITLE
Add boilerplate files for project object

### ISSUE THREAD

**Issue by gowthamrodda** [SeedCompany/cord#16]

**Comment by candleshine** [comment]
Take a look at the apps/api/src/app/organizations folder. Those files implement the API code to provide CRUD-like operations on the libs/data/src/organizations.ts model file.

Use /libs/data/src/project/project.ts as a model

- [ ] create apps/api/src/app/project/
- [ ] create the associated files in that directory
- [ ] create libs/data/src/project/
- [ ] create its associated files

**Comment by CarsonF** [comment]
Depends on #16
