### ISSUE TITLE
Add boilerplate for internship/engagement/engagement

### ISSUE THREAD

**Issue by candleshine** [SeedCompany/cord#31]
Take a look at the apps/api/src/app/organizations folder. Those files implement the API code to provide CRUD-like operations on the libs/data/src/organizations.ts model file.

Use /libs/data/src/internship/engagement/engagement.ts as a model

create apps/api/src/app/internship/engagement/
create the associated files in that directory
create libs/data/src/internship/engagement/
create its associated files

**Comment by CarsonF** [comment]
Depends on #32
