### ISSUE TITLE
Add boilerplate for user/profile

### ISSUE THREAD

**Issue by candleshine** [SeedCompany/cord#39]
Take a look at the apps/api/src/app/organizations folder. Those files implement the API code to provide CRUD-like operations on the libs/data/src/organizations.ts model file.

Use /libs/data/src/user/profile.ts as a model

- [ ] create apps/api/src/app/user/profile/
- [ ] create the associated files in that directory
- [ ] create libs/data/src/user/profile/
- [ ] create its associated files

**Comment by CarsonF** [comment]
Depends on #40 #39 #38 #37 #36
