### ISSUE TITLE
Add boilerplate for user/user-role

### ISSUE THREAD

**Issue by candleshine** [SeedCompany/cord#41]
Take a look at the apps/api/src/app/organizations folder. Those files implement the API code to provide CRUD-like operations on the libs/data/src/organizations.ts model file.

Use /libs/data/src/user/user-role.ts as a model

- [ ] create apps/api/src/app/user/user-role/
- [ ] create the associated files in that directory
- [ ] create libs/data/src/user/user-role/
- [ ] create its associated files

**Comment by CarsonF** [comment]
Needs security discussion(s) first

**Comment by CarsonF** [comment]
@ibohalsinghkoijam this was not in the _Approved for Work_ column. Please only pull from there.
