### ISSUE TITLE
GraphQL: Organizations v1

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord#8]
CRUD + find on the graphql organization resolver

**Comment by CarsonF** [comment]
Resolver is done. Service needs to be implemented

**Comment by michaelmarshall** [comment]
Issue moved to [SeedCompany/cord-api-v3 #1](https://github.com/SeedCompany/cord-api-v3/issues/1) via [**ZenHub**](https://www.zenhub.com/)
